### PR TITLE
Add Safari extension

### PR DESCRIPTION
**Pull request by rdev**
Adds Safari extension
Converted from Firefox using Xcode web extension converter with no additional changes besides app icon adjustment 😄 

Tested and confirmed working on macOS Monterey, not tested (yet) on iOS/iPadOS. Might require tweaks there since iOS does not support persistent background pages and conversion threw up a warning

### Screenshots

Screen Shot 2021-12-01 at 18 26 23

Screen Shot 2021-12-01 at 18 26 26

### App Store
I can publish it to the App Store with permission from maintainers if needed 

re: #127

### CODE REVIEW

**Comment by rdev** [comment]
Turned off persistence, confirmed working on iPadOS 15.0.2 and Monterey 12.0.1

IMG_0105

IMG_0107

**Comment by rdev** [comment]
Doesn't work on iOS because of a layout difference between desktop and mobile but seems like an easy fix, don't merge this yet 😄

**Comment by irlcatgirl** [comment]
Are there plans to support the extension on Safari for iOS or should I create a separate issue?

**Comment by rdev** [comment]
iOS needed some more finessing since mobile YouTube does things a little differently (namely it seems to overwrite the button text dynamically at some points)

Confirmed working reliably on iOS now

:shipit: 

------

IMG_6370

**Comment by rdev** [comment]
Generally a maintainer would do it but idk if @Anarios has Apple Developer membership. I can submit it from my account if necessary

**Comment by irlcatgirl** [comment]
Let’s wait for @Anarios to chime in. If they don’t have a membership I’m sure your help would be appreciated. Hopefully Apple doesn’t give us a hard time 👎🤪

**Comment by mattphelps-8451** [comment]
This is awesome work @rdev thanks for the quick turnaround on this strong feature add

**Comment by Anarios** [comment]
Do you mind if I publish it myself? Do you have time to resolve merge conflicts plz?

**Comment by irlcatgirl** [comment]
If they cannot, I can take a look on Monday afternoon and resolve it on my end. I think the point of asking you first was so you could publish the extension on your account if you have one but we were unsure :-)

**Comment by programmishka** [comment]
@rdev 
Please create a reverse pull request on your fork to be able to merge changes from the original repository.
It would be nice if you could also make the extension compatible with old versions of MacOS, i.e. Catalina.

**Review by danieleremin — APPROVED** [review]

**Comment by bobbelkl** [comment]
Any progress here?

**Comment by iMonZ** [comment]
Hey guys you can publish the app with my developer account.
Just let me know.
Would be really great since I’m using YouTube in the browser a lot kn my iPad.

**Comment by onodera-punpun** [comment]
Could a binary or something be uploaded already, while we we wait for this to get merged and added to the appstore?

**Comment by MaxG-Enpal** [comment]
> Could a binary or something be uploaded already, while we we wait for this to get merged and added to the appstore?

That would be great!

**Comment by onodera-punpun** [comment]
I tried converting it yesterday, and whilst the extension button and popup worked just fine, it didn't actually display the dislike count on YouTube. Something might have changed since the initial conversion.

**Comment by Anarios** [comment]
Closing due to inactivity

**Comment by iMonZ** [comment]
> Closing due to inactivity

Can this be reopened please?
This issue is pretty important!

**Pull request closed without merging**
