### PR TITLE
Implement webpack to use ES6 modules

### PR DESCRIPTION
**Pull request by leonbubova**
## Summary
I added webpack to the project, to be able to use ES6 modules which let's us split up files into modules. This is related to #282 since the changes in there, won't work without webpack and modules.

## What
- Create package.json to handle dependencies
- Add webpack and babel to project
- Create script `npm run bundle` to enable automatic rebuilding of source files on save
- Update `CONTRIBUTE.md` with npm setup

## Why
- To be able to use ES6 modules, which increases code maintainability
- Makes it possible to (after I cleaned it up again) merge #282

### CODE REVIEW

**Comment by leonbubova** [comment]
Is it correct that 6 approving reviewers are required for this PR? That seems a bit hefty 😅

**Review by glenlalo — COMMENTED** [review]
It would be good if you may change the commit message to something else and not just wip

**Comment by leonbubova** [comment]
> It would be good if you may change the commit message to something else and not just wip

Isn't it getting squashed automatically?

**Comment by glenlalo** [comment]
@leonbubova Have you tried loading the extension in firefox? I'm getting this error: `Unsupported manifest version: 3`
In chrome works fine :)

**Comment by leonbubova** [comment]
I think for Firefox you have to rename manifest.json to manifestv3.json and manifestv2.json to manifest.json. But let me double check that as well.

**Comment by leonbubova** [comment]
Yes just checked, after renaming the `manifestv2.json` to `manjfest.json` it works.

**Comment by glenlalo** [comment]
> I think for Firefox you have to rename manifest.json to manifestv3.json and manifestv2.json to manifest.json. But let me double check that as well.

Thanks, after renaming, works in both browsers without having to rename again 👍  Can you push the fix?

**Comment by leonbubova** [comment]
> > I think for Firefox you have to rename manifest.json to manifestv3.json and manifestv2.json to manifest.json. But let me double check that as well.
> 
> Thanks, after renaming, works in both browsers without having to rename again 👍 Can you push the fix?

Just did

**Review by glenlalo — APPROVED** [review]

**Comment by Anarios** [comment]
One of the biggest PRs to extension code so far, thanks so much.

**Pull request merged**
