### PR TITLE
Make `select` elements have a dark background

### PR DESCRIPTION
**Pull request by rakleed**

### CODE REVIEW

**Comment by rakleed** [comment]
@Anarios please take a look

**Comment by rakleed** [comment]
@Anarios could you take a look please?

**Comment by rakleed** [comment]
@Anarios could you take a look please?

**Comment by rakleed** [comment]
@Anarios could you take a look, please?

**Comment by rakleed** [comment]
@Anarios could you take a look, please?

**Comment by Anarios** [comment]
So sorry.

**Pull request merged**
