### PR TITLE
ESLint Integration

### PR DESCRIPTION
**Pull request by PickleNik**
reimplemented #67 
added VSCode config to README
fixed smol iOS scrolling issue
added auto-linter that runs on changes to /Website folder
Screen Shot 2021-12-15 at 1 32 54 AM

### CODE REVIEW

**Comment by PickleNik** [comment]
I think I broke something, don't merge it yet 😬

**Comment by PickleNik** [comment]
files linted. I will rebase and update if conflicts arise.

**Comment by DARKDRAGON532** [comment]
Probably add a workflow so it automatically builds a page when theres a push to the Website folder

**Comment by PickleNik** [comment]
> Probably add a workflow so it automatically builds the page when theres a push to the Website folder

Do you mean in GitHub actions?
What if there's multiple commits to the /Website before it's deployed?
You don't need it built before deployment.
Or did you mean to say "automatically lints"?

**Comment by DARKDRAGON532** [comment]
> > Probably add a workflow so it automatically builds the page when theres a push to the Website folder
> 
> Do you mean in GitHub actions? What if there's multiple commits to the /Website before it's deployed? You only need it built once before deployment. Or did you mean to say "automatically lints"?

I guess if it's not an hassle to build the website before deploying.
Add an action for linting on push and prs i guess

**Comment by PickleNik** [comment]
> > > Probably add a workflow so it automatically builds the page when theres a push to the Website folder
> > 
> > 
> > Do you mean in GitHub actions? What if there's multiple commits to the /Website before it's deployed? You only need it built once before deployment. Or did you mean to say "automatically lints"?
> 
> I guess if it's not an hassle to build the website before deploying. Add an action for linting on push and prs i guess

You single-handedly forced me to learn GH Pages and Actions, thank you :)

**Comment by DARKDRAGON532** [comment]
> > > > Probably add a workflow so it automatically builds the page when theres a push to the Website folder
> > > 
> > > 
> > > Do you mean in GitHub actions? What if there's multiple commits to the /Website before it's deployed? You only need it built once before deployment. Or did you mean to say "automatically lints"?
> > 
> > 
> > I guess if it's not an hassle to build the website before deploying. Add an action for linting on push and prs i guess
> 
> You single-handedly forced me to learn GH Pages and Actions, thank you :)

you never asked me for help

**Review by DARKDRAGON532 — APPROVED** [review]

**Comment by PickleNik** [comment]
happyharold

**Comment by DARKDRAGON532** [comment]
force push 💀

**Comment by PickleNik** [comment]
> force push 💀

why not?

**Comment by PickleNik** [comment]
> Probably add a workflow so it automatically builds the page when theres a push to the Website folder

added weblint.yml in the last commit, thanks 👍🏼

**Review by Anarios — APPROVED** [review]
Amazing

**Pull request merged**
