### PR TITLE
Add Japanese README | Add its link

### PR DESCRIPTION
**Pull request by Hayao0819**

### CODE REVIEW

**Review by aaronkerckhoff — CHANGES_REQUESTED** [review]
Thank you very much for your contribution. There is only one thing you have to change, I think:

**Comment by Hayao0819** [comment]
Sorry, I have just fixed it.

**Comment by Hayao0819** [comment]
Thank you. I did not know it.

**Comment by Hayao0819** [comment]
Thanks Done.

**Review by Hayao0819 — COMMENTED** [review]
I applied it, but I may have misused it.

**Pull request merged**
