### PR TITLE
update rating bar on input

### PR DESCRIPTION
**Pull request by cupiditys**
* rating bar updates when you click like/dislike
* changed "response.likes && response.dislikes" to "response.viewCount" to prevent errors on videos with no likes
> 
> gif

### CODE REVIEW

**Comment by JacynoAdam** [comment]
Doesn't changing to accepting `response.viewCount` cause a problem with less accurate YouTube data overwriting API data? Specifically, I mean, as far as I could tell, YouTube reponse would always return 0 dislikes (as it's hidden everywhere now), and if the value of dislikes is not checked (`if (response.likes && response.dislikes)`) would it not cause a number with dislikes from API reponse being overwritten with data scrapped from YouTube with 0 dislikes?

Sorry if I'm missing something obvious, not very experienced with extensions.

**Comment by Anarios** [comment]
Some conflicts, sorry :( Have time to resolve?

**Comment by cupiditys** [comment]
there

**Comment by cupiditys** [comment]
also fixed #232 as you can see

**Pull request merged**
