### PR TITLE
Patch: Remove unneeded function after YT-API changed and fixed loading of extension in Firefox

### LINKED ISSUE #320: (Bug): Loading RYD as a temporary extension does not work in Firefox
### Browser

Firefox

### Browser Version

latest

### Extension or Userscript?

Extension

### Extension/Userscript Version

latest

### Video link where you see the problem

null

### What happened?

A bug happened!

### PR DESCRIPTION
**Pull request by glenlalo**
- Number formatting is not needed anymore, since the extension does not fetch dislike data from YT.
- Loading as temporary extension in Firefox is fixed #320

### CODE REVIEW

**Comment by Anarios** [comment]
manifest file is for chrome. manifest v2 is used with FF, so what you did breaks chrome.

**Comment by glenlalo** [comment]
@Anarios I tested in chrome and it works too.

**Comment by Anarios** [comment]
@ghost, yea - but it changes manifest version, which prevents from publishing to chrome store

**Comment by Anarios** [comment]
This is done with webpack now.

**Pull request closed without merging**
