### PR TITLE
Website & Extension improvements

### PR DESCRIPTION
**Pull request by PickleNik**
- removed jitter when switching between scrollable and non-scrollable pages
 - replaced default value for extension version from `2.0.0.3` to `loading` on Troubleshooting page.
 - what the commits below say + screenshots :)

### CODE REVIEW

**Comment by PickleNik** [comment]
Screen Shot 2022-01-10 at 1 53 17 PM
image
image
Screen Shot 2022-01-10 at 5 17 11 PM

**Comment by Frontesque** [comment]
image


I would change this to just "{OS} is not supported. Consider upgrading."
It's simpler and a bit more professional

**Comment by Anarios** [comment]
Couple merge conflicts :(

**Comment by PickleNik** [comment]
> Couple merge conflicts :(

one sec, will rebase

**Comment by PickleNik** [comment]
ready to merge @Anarios

**Pull request merged**
