### PR TITLE
Add support for new youtube layout in UserScript

### PR DESCRIPTION
**Pull request by hyperstown**
Hi I've added support for new YouTube layout in UserScript for both desktop and mobile version.
I've also checked if this didn't break old layout and as far as I can tell it works without an issue.

Resolves: #748, #666

### Screenshots:

Mobile:
image

Desktop:
image

### CODE REVIEW

**Comment by pruebaz** [comment]
I tried your latest commit but the dislike its shown in the share icon:

https://i.imgur.com/9aNloWn.png

**Comment by hyperstown** [comment]
> I tried your latest commit but the dislike its shown in the share icon:
> 
> https://i.imgur.com/9aNloWn.png
I pushed fix. Could you please try it?

**Comment by pruebaz** [comment]
> > I tried your latest commit but the dislike its shown in the share icon:
> > https://i.imgur.com/9aNloWn.png
> 
> Fix pushed. Could you please try it?

working fine now!

**Comment by t0astbr0t** [comment]
Works like a charm for issue "RYD no longer working on Safari 16 with Tampermonkey script #775".

Thank you very much!

**Comment by Beariddle** [comment]
Setup:
- Browser: Firefox 106.0.2
- Extension: FireMonkey 2.65

Came along to give my thanks for this fix. It works like a charm! Thank you very much.👍

**Review by Floyd77 — APPROVED** [review]

**Comment by AshtakaOOf** [comment]
Why is this not being merged?

**Comment by hyperstown** [comment]
> Why is this not being merged?

It seems that UserScript is quite a bit behind extension so maybe maintainers don't won't to change anything before refactor?
@Anarios could you please confirm or state any plans regarding UserScript development? If you plan refactor I'm happy to help.

**Comment by Anarios** [comment]
Yes, I wasn't actively keeping userscript updated with the rest of extension, my bad.

**Comment by hyperstown** [comment]
No worries. I'm using UserScript everyday on my phone so I'll keep on submitting fixes whenever I find something broken :D

**Pull request merged**
