### PR TITLE
colorize buttons and ratio bar

### LINKED ISSUE #218: (Feature Request): Colours
### Extension or Userscript?

Extension

### Request or suggest a new feature!

Firstly, thank you very much for providing this useful extension.
What would make it even better would be an option to have the parts of the like/dislike bar and possibly the thumbs coloured red and green as they used to be in earlier layouts of youtube

### Ways to implement this!

_No response_

### Can you work on this?

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by cyrildtm**
Resolves #218
Using user options (#387)

I'm recreating #436 which I screwed up with rebasing. Didn't want to spam the PR with upstream commit records. 

Users can turn on colors for buttons and ratio bars separately, and choose a color scheme (like/dislike) for both. 
Here are the three color schemes at present: 

Capture

### CODE REVIEW

**Comment by cyrildtm** [comment]
Right now there's a cherry pick from #442 in order to compile. Let me know if I need to make changes.

**Comment by Anarios** [comment]
Are duplicates necessary?

**Comment by cyrildtm** [comment]
> Are duplicates necessary?

Hi! If you meant duplicate definitions of functions, please see my reply in the other PR: https://github.com/Anarios/return-youtube-dislike/pull/435#discussion_r799829906

Basically I can't mix the content script's workspace (or whatever that's called in js) and the popup's one. 
I followed the way the first custom setting (disable vote submission) is implemented -- I think it defines the same functions twice, too.

**Comment by Anarios** [comment]
Thanks!

**Pull request merged**
