### PR TITLE
Add safari extension

### LINKED ISSUE #127: (Feature Request): Safari extension
### Extension or Userscript?

Extension

### Request or suggest a new feature!

It would be nice if you made a Safari extension. Since starting with version 14, support for the WebExtensions API has appeared. And from version 15 there will be support for Safari for iOS. More details: developer.apple.com/documentation/safariservices/safari_web_extensions

### Ways to implement this!

_No response_

### Can you work on this?

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by onodera-punpun**
I know there is #133, but that PR seems a bit stale. This one is up to date with master, and makes use of webpack to build the safari extension.

Note that I have only tested this on MacOS, and not iOS.

Closes #127.

### CODE REVIEW

**Comment by DARKDRAGON532** [comment]
if someone tests this on iOS that would be really cool

**Comment by rdev** [comment]
https://github.com/Anarios/return-youtube-dislike/pull/133 implements iOS and is only stale because it "requires 6 reviews to be merged" and no one is looking at it. These changes are better merged there

**Comment by marcizhu** [comment]
@rdev #133 is stale because it had merge conflicts for months now, not because "no one is looking at it".

Now that #133 has been closed due to inactivity maybe its time to combine both PRs into a single one and merge it into the main branch.

**Comment by rdev** [comment]
@marcizhu it was ready to merge before the conflicts

**Comment by marcizhu** [comment]
I totally agree on that, but then there were merge conflicts and that's why it never got merged. Regardless, lets not go off-topic. Can we please get either #133, #443 or a mix of both merged so that we can have an extension for Safari? 😄

**Comment by yieldinov** [comment]
Why no one is looking at it?

**Comment by iMonZ** [comment]
Anything new here?

**Comment by mishushakov** [comment]
@iMonZ you can just download free Userscripts app from the App Store
https://apps.apple.com/de/app/userscripts/id1463298887?l=en

enable it in Safari then click on "Userscript" on the install page
https://returnyoutubedislike.com/install

works great for me both on Mac and iPhone!

**Review by anthonyhuang07 — APPROVED** [review]

**Comment by onodera-punpun** [comment]
Closing due to inactivity. Someone can make the same PR for the fourth time after which then can be ignored.

**Pull request closed without merging**
