### PR TITLE
Website fixes & improvements (!merge before deployment)

### PR DESCRIPTION
**Pull request by PickleNik**
## Fixes navbar bug:
Current version (undeployed)
Screen Shot 2021-12-03 at 7 34 46 PM
This version
Screen Shot 2021-12-03 at 7 58 50 PM

### Improves spacing:
Current version
Screen Shot 2021-12-03 at 8 05 33 PM
This version
Screen Shot 2021-12-03 at 8 05 48 PM

### FAQ fixes:
Before:
https://user-images.githubusercontent.com/31113245/144694644-f42f7285-b8b7-451d-bf3a-ed8357777f56.mov

After:
https://user-images.githubusercontent.com/31113245/144694650-cac5115a-8d64-454a-a76e-0448277a3530.mov

### Route Transitions: 
Before:
https://user-images.githubusercontent.com/31113245/144694733-f024d8c2-7d05-4b1d-ab04-b36039aab0b4.mov

After:
https://user-images.githubusercontent.com/31113245/144694737-33a3566e-0b73-404b-a75a-afe58b1b25dd.mov

## Overall After: 
https://user-images.githubusercontent.com/31113245/144696422-8ef87f78-e37f-44b9-a8aa-110c47d94ebd.mov

## New logo animation:
https://user-images.githubusercontent.com/31113245/144723004-31981f8f-8f78-4a4a-8776-3796da3e2666.mov

### CODE REVIEW

**Review by Nightcaat — CHANGES_REQUESTED** [review]
For accessibility reasons, you might want to use the `prefers-reduced-motion` CSS media query to not show the animations if the user prefers reduced motion.

**Comment by PickleNik** [comment]
> For accessibility reasons, you might want to use the `prefers-reduced-motion` CSS media query to not show the animations if the user prefers reduced motion.

Noted 👍
Will add to PR today

**Comment by PickleNik** [comment]
added prefers-reduced-motion, Github is red and scary and says it needs a review 👀

**Comment by PickleNik** [comment]
@Nightcaat

**Comment by Anarios** [comment]
Will review shortly, thanks so much

**Comment by PickleNik** [comment]
Note: added new logo on landing page (see last vid in commit description)
@Nightcaat will make a PR for favicon and og:image soon.
It's in the last commit only, include it if you like it :)

**Review by Anarios — APPROVED** [review]

**Pull request merged**
