### PR TITLE
Feature 292 - add option to disable vote submission

### PR DESCRIPTION
**Pull request by himanshudabas**
Changes:
* new icon is added which is used when voting is disabled
* popup.js, content-script, background-script listens to storage change event so that they can all stay in sync without passing messages among themselves
* advanced setting is added in popup.html
* voting is enabled by default

<hr>

What's not implemented yet:
* time based re-enable voting

### CODE REVIEW

**Comment by mattphelps-8451** [comment]
Don't forget to do Userscript too

**Comment by mphelp** [comment]
Don't forget to include Userscript too

**Comment by mphelp** [comment]
re: #315

**Comment by himanshudabas** [comment]
oh there's already a PR for this. 
I am sorry I completely missed that. I thought I was the only one working on this feature.

> Don't forget to include Userscript too

I don't really know how to work with userscript. I'll take a look though.

**Comment by Anarios** [comment]
A big PR with conflicts was merged, so there are some conflicts, I could resolve them in my branch (but then you'd lose the contributor stats, if you care about them). Or I could wait for you to resolve. Whichever way is better for you

**Comment by himanshudabas** [comment]
@Anarios 
resolved the merge conflicts and did some refactoring.

**Comment by Anarios** [comment]
Thanks so much.

**Pull request merged**
