### PR TITLE
change text from "DISLIKES DISABLED" to "DISLIKE"

### PR DESCRIPTION
**Pull request by tacohitbox**
The text doesn't fit the UI currently if the likes/dislikes are disabled.
The current UI state with this extension. Note how the DISLIKES DISABLED looks out of place.

This fork would feel more at home here.
The state of this fork. The UI looks normal now.

### CODE REVIEW

**Review by DivyanshByte — APPROVED** [review]

**Comment by thesusian** [comment]
It was mad like this to not confuse users to think that the extension isn't working

**Comment by tacohitbox** [comment]
> It was mad like this to not confuse users to think that the extension isn't working

There is a more elegant way of doing that. Perhaps making the bar a certain colour. The current way looks wrong.

**Comment by MZPL** [comment]
The current one seems more straightforward to me. It didn't really bothered me when I saw it for the first time.

**Comment by tacohitbox** [comment]
> The current one seems more straightforward to me. It didn't really bothered me when I saw it for the first time.

It's jarring to me personally. I guess it isn't for everyone though.

**Comment by thesusian** [comment]
> > The current one seems more straightforward to me. It didn't really bothered me when I saw it for the first time.
> 
> It's jarring to me personally. I guess it isn't for everyone though.

You can discuss it on discord with other devs if you want :)

**Comment by tacohitbox** [comment]
Closing because of this. Looking forward to newer versions of the addon!
image

**Pull request closed without merging**
