### PR TITLE
Fix like numbers re-format

### LINKED ISSUE #604: (Bug): Like button number showing up weird whenever i click like button
### Browser

Brave Browser

### Browser Version

Version 1.38.115 Chromium: 101.0.4951.64 (Official Build) (64-bit)

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.1

### Video link where you see the problem

any video with alot of likes

### What happened?

لقطة الشاشة 2022-05-11 160245
This shows up when i select 123 thousand number format

لقطة الشاشة 2022-05-11 160427
This shows up when i select 123K number format

(it stays until i refresh the page)

### How to reproduce/recreate?

Basically just like a video with alot of likes

### LINKED ISSUE #605: (Bug): Seemingly random like number on videos
### Browser

Brave Browser 

### Browser Version

1.38.111

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=f-HtmE0U7T8

### What happened?

MacOS - 12.4 Beta

Not an isolated incident, but this number keeps coming up on random videos for some reason.
CleanShot 2022-05-11 at 18 35 09
 

### How to reproduce/recreate?

Not sure how to reproduce it seems to be at random for me.

### LINKED ISSUE #645: (Bug): Duplicating likes on second click...
### Browser

Chrome

### Browser Version

Chrome 102, Windows 11.

### Extension or Userscript?

Extension

### Extension/Userscript Version

v3.0.0.2

### Video link where you see the problem

Any video under 1K likes, for example: https://www.youtube.com/watch?v=KJGD4RdwKWU

### What happened?

Sometimes when I watch a video, then click on the like button, this happens:

https://user-images.githubusercontent.com/95201376/173156123-2a6fa002-347d-4ef1-b820-8569fe316a9c.mp4

I forked the repo and traced **EVERYTHING**, but I can't seem to find where the problem is exactly.

### How to reproduce/recreate?

Go to a video with less than 1,000 likes, [Like this one](https://www.youtube.com/watch?v=KJGD4RdwKWU),
and click the like button two or three times. It will duplicate the like number, almost as if you used
the += operator, (in the source code at the reassigning of "likeButton.textContent"), but there is no
indication of that.

The only thing that I think might be the problem is you are trying to add an integer to a string.

### LINKED ISSUE #647: Like button counter doesn't update if "123456" number format is used
### Browser

Firefox

### Browser Version

102 (beta)

### Extension or Userscript?

Extension

### Extension/Userscript Version

3.0.0.1

### Video link where you see the problem

https://www.youtube.com/watch?v=i1AHCaokqhg

### What happened?

Like button counter does not get updated after liking/unliking a video with "123456" number format enabled:

firefox_R6y0jYQP3B

### How to reproduce/recreate?

Set the extension settings like this:

изображение

and try to like any video with enabled like/dislike counter.

### LINKED ISSUE #650: Fix "adding other numbers after the "like or dislike" button
Other numbers keep appearing when you either click "like or dislike"

### PR DESCRIPTION
**Pull request by cyrildtm**
When like button is clicked, only one of the two aria-label attributes gets updated. Use the correct one to reflect latest like count. Affects user option "re-format like numbers" Related: #561

When like button is clicked, YT will update like count. This conflicts with user option "re-format like numbers". Force update like number. Related: #584

Since official like count is still available, avoid using API server response. Clarify user option re-format like number does not work on Shorts. Related: #581

fixes #605 
fixes #604
probably fix issues #496 and #631 but the issue's OP is not responding for further diagnostic details, so can't be sure

closes #645
closes #647
closes #650

### CODE REVIEW

**Comment by ErykDarnowski** [comment]
Hey, I'm curious why the current solution is to just say the feature doesn't work on shorts instead of implementing the fix proposed in pull #581?

**Review by tomkap011 — APPROVED** [review]

**Comment by hungdoansy** [comment]
Hej, I'm a bit curious why you explicitly compared something boolean to true/false (=== true, !== false)?

**Comment by hungdoansy** [comment]
> @hungdoansy Javascript is an ambiguous language. The variable doesn't have to be a boolean in order for the code to run. For example when a variable is a string or `undefined`, `if ()` will silently branch into true or false cases respectively, rather than failing to run as a feedback. It's a general procedure to make up this bad design decision by explicitly comparing the variable to true or false. You don't have to do this in other languages like Python or C, they are more strict languages.

Thanks. That makes so much sense

**Comment by s5bug** [comment]
This does not fix #647 for me. Tested on https://youtu.be/I1xjCMqqrgY

image

image

**Comment by s5bug** [comment]
I did not at the time. That fixed it, thanks!

**Pull request merged**
