### PR TITLE
Fixes, Enhancements and Consistency

### PR DESCRIPTION
**Pull request by Arora-Sir**
1. Optimized the fetching scheme to get the data before the video dislike button appeared.
2. Fetch data from the server is now separate from set button data to get Data from the server even before appearing of a dislike button. As soon as the buttons appear, it refreshes the data.
3. window.returnDislikeButtonlistenersSet was giving an error in the chrome browser and could not register buttons, so fixed it.
4. cLog boolean isTester check for developers/testers.
5. Beautify/Consistency in code has been created.

### CODE REVIEW

**Comment by Arora-Sir** [comment]
#828 : fixes after this.

**Comment by Rizxcviii** [comment]
For point 5, it might be a good idea to implement a .prettierrc config file in the route of the directory. This will enforce prettier to use the formatting specified within that file, rather than our own. My IDE will most likely overwrite the prettier changes made here.

**Comment by hyperstown** [comment]
> 4. cLog boolean isTester check for developers/testers.

I'm not sure is that a good idea. Some cLogs should be left in production just to easy verify state without creating test environment.

**Comment by hyperstown** [comment]
image

image

**Comment by hyperstown** [comment]
Also your changes breaks dislikes number when user will click back in the browser.

Original video:
image

Click next video:
image

Click back in the browser:
image

The number of dislikes remains same as in the second video. 

I've also double checked and current version `3.1.0` doesn't have that issue.

**Comment by Arora-Sir** [comment]
> > 4. cLog boolean isTester check for developers/testers.
> 
> I'm not sure is that a good idea. Some cLogs should be left in production just to easy verify state without creating test environment. 

Hey, I've just added the boolean for it at the top, in case someone don't want all the logs again and again for every video they open, devs or non-devs, can easily see the variable at top and stop the logs.

**Comment by Arora-Sir** [comment]
> Also your changes breaks dislikes number when user will click back in the browser.
> 
> Original video:
> image
> 
> Click next video:
> image
> 
> Click back in the browser:
> image
> 
> The number of dislikes remains same as in the second video. 
> 
> I've also double checked and current version `3.1.0` doesn't have that issue.


I'm wondering why this issue presists! I'll look into it and will make sure this doesn't happen!

**Comment by hyperstown** [comment]
> > > 4. cLog boolean isTester check for developers/testers.
> > 
> > 
> > I'm not sure is that a good idea. Some cLogs should be left in production just to easy verify state without creating test environment.
> 
> Hey, I've just added the boolean for it at the top, in case someone don't want all the logs again and again for every video they open, devs or non-devs, can easily see the variable at top and stop the logs.

Youtube itself spams in console like crazy so I don't really see a point in removing 2 or 3 additional messages which vast majority of users will not see as I'm sure only devs and testers watch youtube with dev tools enabled. 
But sure I guess it's good to have an option to disable it. I just think it should be enabled by default.

**Comment by Arora-Sir** [comment]
@hyperstown I've looked into the abovementioned issue and solved it in #842.

And console logs for this script are by default enabled, but if someone (like me) wants to remove it from devs console (who has so many other things in logs going on), they can remove it easily by just setting the one variable false.

**Comment by Arora-Sir** [comment]
@hyperstown Thanks for letting me know all of this.

Ahh, my bad...sorry! I know how to check in the Laptop/PC browser, but never used any script for mobile devices, and the thing about the new pull, I didn't know about that at that moment and did the pull request, but after an hour, did commit to this pull request again. Console logs check can be edited; that's why I've given the code edit access to the moderator while doing requests for pulling. (don't know how this code can be editable feature works when pushing code, though). Anyways, never mind. I'll try someday on the weekend with all these things again:

1. Console logs "Turn On" by default.
2. No errors in the console.
3. Working on the phone too.
4. No use of prettier.😃 

Till then, have a great week ahead. #HappyCoding 🤟🏻

**Comment by hyperstown** [comment]
Sure, no problem! Happy to help.

While making changes to code you should always test:
- Supported browsers (Chromium, Firefox, Safari). 
- Supported YouTube designs (YouTube often has two layouts)
- Mobile version (Firefox has cool option that allows you to spoof UA while testing mobile screens. You can't test mobile YT with desktop UA)
- YT Shorts 
Mobile version is really hard to work with in my experience as YouTube keeps updating DOM even when you click something seemingly unrelated like resolution drop-down. It's not impossible to work around this but it makes changes difficult :P

As for pull request, just to let you know, there's option to set PR as draft. So if you need to fix something that was discovered later you can always set status to draft and work on it whenever you have time.

Anyway you too have a great week! And good luck!

**Pull request closed without merging**
