### PR TITLE
its, not it's

### PR DESCRIPTION
**Pull request by radzo73**

### CODE REVIEW

**Review by lucaspar — APPROVED** [review]

**Review by Nightcaat — APPROVED** [review]

**Comment by krystian3w** [comment]
`It is` no match?

**Comment by CurtisTD** [comment]
Now _this_ is how you get you Open Source Software badge

**Review by DARKDRAGON532 — APPROVED** [review]

**Comment by krystian3w** [comment]
These have many github accounts:



Also this no prove that me known all English grammar on perfect mode.

**Review by Anarios — APPROVED** [review]

**Comment by Anarios** [comment]
Thanks

**Pull request merged**
