### PR TITLE
Add 5 Star rating

### LINKED ISSUE #105: [Feature Request] Add stars, just like in the old youtube
Add the star ranking system to the addon, where each video can be ranked from 1 to 5 stars by a user.

### PR DESCRIPTION
**Pull request by sy-b**
resolves #105 

RYDStarRatingPage

<br>

Credits:

Some code is ~~stolen~~ browed from [Mads Stoumann](https://dev.to/madsstoumann)'s [post](https://dev.to/madsstoumann/star-rating-using-a-single-input-i0l). Also available on https://codepen.io/stoumann/pen/yLbYOdz

### CODE REVIEW

**Comment by PickleNik** [comment]
wow finally somebody made it after i promised it 6 months ago and never spoke of it again
thank you 🙏🏼

**Comment by sy-b** [comment]
> Just to make sure we aren't using any copyrighted "star icon" SVGs right?

MIT License - https://blog.codepen.io/documentation/licensing/

**Comment by sy-b** [comment]
Some more feature suggestions:

- Modify SVG 
  - color
  - size
  - the SVE itself; custom svg (heart, rockets, etc)

- Rating using the stars
  - optionally removing like & dislike button

**Comment by sy-b** [comment]
@PickleNik 
Another reminder ->
You have to update https://github.com/Anarios/return-youtube-dislike/projects/1

**Comment by Ione15** [comment]
Add option to show only stars, only thumbs (default), or both

**Pull request merged**
