### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **18%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /Icons/Discord.gif | 300.78kb | 206.55kb | 31.33% |
| /Extensions/combined/icons/server.svg | 1.09kb | 0.92kb | 16.07% |
| /Website/static/ui/troubleshooting.png | 465.90kb | 410.15kb | 11.97% |
| /Website/static/ui/abstract.svg | 5.19kb | 4.97kb | 4.31% |
| /Icons/128x128_transparent.jpg | 4.04kb | 3.92kb | 3.00% |
| /Icons/Return Youtube Dislike - Dark.jpg | 32.45kb | 31.52kb | 2.88% |
| /Icons/Return Youtube Dislike - Dark.png | 17.99kb | 17.65kb | 1.86% |
| | | | |
| **Total :** | **827.46kb** | **675.68kb** | **18.34%** |
</details>

---

[📝 docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/imgbot/ImgBot) | [🙋🏾 issues](https://github.com/imgbot/ImgBot/issues) | [🏪 marketplace](https://github.com/marketplace/imgbot)

<i>~Imgbot - Part of [Optimole](https://optimole.com/) family</i>

CREDIT TO @imgbot

### CODE REVIEW

**Comment by PickleNik** [comment]
this will conflict with #575 since website images were replaced by .webp there

**Comment by KendallDoesCoding** [comment]
> this will conflict with #575 since website images were replaced by .webp there

Ok, but it hasn't been merged yet, If it's merged then I'll close this PR and make a new one if required 😄

**Comment by PickleNik** [comment]
Seems like it

**Comment by PickleNik** [comment]
Just removing that file from commit should fix it, no need to optimize that one as it's been replaced by a .webp that's 10 times smaller 👍

**Comment by KendallDoesCoding** [comment]
> Just removing that file from commit should fix it, no need to optimize that one as it's been replaced by a .webp that's 10 times smaller 👍

Oh cool, Will do that, if the img bot wants to optimize that as well, let it lol, but I don't think it will, if the file size is small now.

**Comment by KendallDoesCoding** [comment]
Please confirm if that works @PickleNik

**Comment by PickleNik** [comment]
> Please confirm if that works @PickleNik 

Yop, good to merge

**Review by PickleNik — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
> > Please confirm if that works @PickleNik
> 
> Yop, good to merge

👍

**Comment by KendallDoesCoding** [comment]
Great, pull bot messed up everything.

**Pull request closed without merging**
