### PR TITLE
Troubleshooting (Help) page for the website

### PR DESCRIPTION
**Pull request by PickleNik**
I've chosen an epic video for screenshot example
troubleshooting1
troubleshooting2

### CODE REVIEW

**Review by Frontesque — APPROVED** [review]
This may cause some conflicts with my PR because of my ESLinting but I can sort that out later.

**Comment by PickleNik** [comment]
> This may cause some conflicts with my PR because of my ESLinting but I can sort that out later.

`npm run lint` before merge should help avoid any

**Comment by PickleNik** [comment]
detector
Added platform detector for copypasting

**Comment by Frontesque** [comment]
> detector Added platform detector for copypasting

already done over here as we discussed in the discord
[(my pr)](https://github.com/Anarios/return-youtube-dislike/pull/376)

**Comment by Anarios** [comment]
is it needed after #376 ?

**Comment by PickleNik** [comment]
> is it needed after #376 ?

@Anarios, I assume so, #376 is a debugger tool, and this is the rest of the troubleshooting steps.
I will replace my platform detector button with #376 debugger once all is merged.

**Comment by PickleNik** [comment]
> is it needed after #376 ?

@Anarios, I assume so, #376 is a debugger tool + API Docs, this is Troubleshooting, taken from #troubleshooting channel in Discord. I will replace my "platform detector" button with the debugger tool once all is merged.

**Comment by PickleNik** [comment]
Screen Shot 2022-01-04 at 7 13 25 PM
Screen Shot 2022-01-04 at 7 13 33 PM

**Comment by PickleNik** [comment]
Screen Shot 2022-01-05 at 12 22 01 AM

**Comment by PickleNik** [comment]
Screen Shot 2022-01-05 at 12 57 57 AM

**Review by DARKDRAGON532 — APPROVED** [review]

**Pull request merged**
