### PR TITLE
fixed typos/grammar in FAQ page

### PR DESCRIPTION
**Pull request by GeneticallyModifiedAlex**
The word Dislike was spelt "dislke". this has been fixed
the grammar had some issues in other parts. i have addressed these above.

### CODE REVIEW

**Comment by Anarios** [comment]
Do you have time to resolve conflicts?

**Comment by GeneticallyModifiedAlex** [comment]
> Do you have time to resolve conflicts?

sure thing ill do it now

**Comment by GeneticallyModifiedAlex** [comment]
> Do you have time to resolve conflicts?

The conflicts should be resolved now. If you'd like feel free to run any text by me for review. 
I think your project is admirable and will do what i can. You can find my contact details on my account

**Comment by GeneticallyModifiedAlex** [comment]
this should do it.

**Review by PickleNik — APPROVED** [review]
Cool beans

**Review by Anarios — APPROVED** [review]

**Pull request merged**
