### PR TITLE
Major UI Update + Feature Request Implementation

### PR DESCRIPTION
**Pull request by Frontesque**
**Changes:**
- Improved Extension Click UI
- New Toggle Switches
- Implemented Feature Requests #59 and #93 

image
image

### CODE REVIEW

**Comment by mattphelps-8451** [comment]
@Frontesque @PickleNik Can you explain the intent behind the addition of those toggles?

**Comment by PickleNik** [comment]
> @Frontesque @PickleNik Can you explain the intent behind the addition of those toggles?

Not at the moment, no 😂
I'm guessing those are for settings that @Frontesque will probably finish tomorrow

**Comment by Frontesque** [comment]
> @Frontesque @PickleNik Can you explain the intent behind the addition of those toggles? 

@DARKDRAGON532 actually asked me to add them for something that he is working on. I may use them later but that's the main reason.

**Comment by DARKDRAGON532** [comment]
Basically for some UX and UI configuration

**Review by Nightcaat — APPROVED** [review]

**Review by DARKDRAGON532 — APPROVED** [review]

**Review by Anarios — APPROVED** [review]

**Pull request merged**
