### PR TITLE
add post API example and link to python library

### PR DESCRIPTION
**Pull request by bbilly1**
Extended the API documentation section with an example on how to register and cast your vote.

Also link to the python library I created:
https://github.com/bbilly1/ryd-client

### CODE REVIEW

**Comment by Frontesque** [comment]
This whole page was redone by @PickleNik via PR #377 therefore invalidating this PR.

**Comment by bbilly1** [comment]
@Frontesque Hmm, I don't see any API examples and descriptions for post requests in #377, or am I missing something? So this isn't really a trouble shooting guide, this is an API documentation and integration guide with a link to a Python library implementing the API requests.

This PR started with #328 just for context. But yes, I think documentation should be consolidated in one place.

**Comment by Frontesque** [comment]
> @Frontesque Hmm, I don't see any API examples and descriptions for post requests in #377, or am I missing something? So this isn't really a trouble shooting guide, this is an API documentation and integration guide with a link to a Python library implementing the API requests.
> 
> This PR started with #328 just for context. But yes, I think documentation should be consolidated in one place.

API examples are in my, even earlier PR. #376

**Comment by bbilly1** [comment]
Ah I see. Do you also have an example about how to contribute to the API, aka cast your vote?

**Pull request closed without merging**
