### PR TITLE
Update Documentation & Add Debug Page

### PR DESCRIPTION
**Pull request by Frontesque**
Move the documentation from the readme.md to the website:

image
image
image
image

### CODE REVIEW

**Comment by Frontesque** [comment]
Also added the '/debug' page which lets people give us more info about their device when they're having issues.
(had to edit the extension a little bit for this)

image

**Review by UnderscoreX5 — APPROVED** [review]

**Review by Anarios — APPROVED** [review]

**Comment by Anarios** [comment]
The origin branch is not inside this repository, so I can't resolve conflicts :( 

All conflicts are in generated files - so just discard them - the will be auto-generated again.

I thought they are in gitIgnore already.

**Comment by Frontesque** [comment]
> The origin branch is not inside this repository, so I can't resolve conflicts :(
> 
> All conflicts are in generated files - so just discard them - the will be auto-generated again.
> 
> I thought they are in gitIgnore already.

All good

**Comment by Anarios** [comment]
Just remove the /dist folder, it's in gitignore, should not be added anymore.

**Pull request merged**
